# SOPS Configuration - age Encryption Keys
#
# This file defines which age public keys can encrypt/decrypt secrets.
#
# SETUP:
# 1. Generate age key on production droplet:
#    age-keygen -o /etc/eracun/.age-key
#    age-keygen -y /etc/eracun/.age-key  # Get public key
#
# 2. Add public key below (replace "REPLACE_WITH_PRODUCTION_AGE_PUBLIC_KEY")
#
# 3. For each developer:
#    Developer runs: age-keygen -o ~/.age-key
#    Developer shares: age-keygen -y ~/.age-key
#    Team lead adds developer's public key below

creation_rules:
  # Production environment secrets
  - path_regex: secrets/.*-production\.env\.enc$
    age: >-
      REPLACE_WITH_PRODUCTION_AGE_PUBLIC_KEY

  # Staging environment secrets
  - path_regex: secrets/.*-staging\.env\.enc$
    age: >-
      REPLACE_WITH_STAGING_AGE_PUBLIC_KEY,
      REPLACE_WITH_DEVELOPER1_AGE_PUBLIC_KEY,
      REPLACE_WITH_DEVELOPER2_AGE_PUBLIC_KEY

  # Development environment secrets (all developers can decrypt)
  - path_regex: secrets/.*-dev\.env\.enc$
    age: >-
      REPLACE_WITH_DEV_AGE_PUBLIC_KEY,
      REPLACE_WITH_DEVELOPER1_AGE_PUBLIC_KEY,
      REPLACE_WITH_DEVELOPER2_AGE_PUBLIC_KEY

  # Default: all secrets (if no specific pattern matches)
  - age: >-
      REPLACE_WITH_PRODUCTION_AGE_PUBLIC_KEY,
      REPLACE_WITH_STAGING_AGE_PUBLIC_KEY,
      REPLACE_WITH_DEV_AGE_PUBLIC_KEY

# age public keys format: age1<58 characters>
# Example: age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
